### ISSUE TITLE
Is there any possibility that the connection pool function will be increased?

### ISSUE THREAD

**Issue by shove70** [Paxa/mysql.d#10]
I like this native style library, but mysql.d doesn't seem to have a "connection pool" feature

**Comment by Paxa** [comment]
I have no plans to add it, but it would be nice to have.
Is there any generic thread pools for D?
Please feel free to submit PR

**Comment by shove70** [comment]
Thank you, I also plan to write a generic connection pool for D, but the time may be delayed some.

**Comment by heketang** [comment]
Hi,Mr Paxa.I have a problem when i use it in windows.the error indicates that the  libmysql.lib cannot be opened. also ,i can use mysql in my 'cmd ' ,what next to do? Do I need to download mysqlclient separately。

**Comment by Paxa** [comment]
Hi @heketang I don't know where libmysql.dll should be, I found some info that you may need to install MySQL connector https://dev.mysql.com/downloads/connector/c/

What is error message do you get?

**Comment by heketang** [comment]
Ok,I thank it'i useful to me,i will try it and give you the message.

**Comment by shove70** [comment]
Hi, Paxa:
Suddenly found that there is a universal thread pool in Phobos.
t's in std.parallelism.

I used it, the effect was good：
https://github.com/shove70/async/blob/master/libasync/src/async/thread.d
