### ISSUE TITLE
Cannot compile on Linux - ld -lmysqlclient failing

### ISSUE THREAD

**Issue by grogancolin** [Paxa/mysql.d#6]
Hi,

Having some trouble compiling on Linux (ubuntu 14.10)
ld cannot find mysqlclient.lib

Compiling using dmd...
Linking...
/usr/bin/ld: cannot find -lmysqlclient
collect2: error: ld returned 1 exit status

I have installed the mysql client and server however, and in my /usr/lib directory is:
$ ls /usr/lib/x86_64-linux-gnu/ | grep sql
libmysqlclient_r.so.18
libmysqlclient_r.so.18.0.0
libmysqlclient.so.18
libmysqlclient.so.18.0.0

Anyone know how to solve this?
Thanks.

**Comment by 5uh417** [comment]
@Paxa What is the equivalent for Centos.
