### ISSUE TITLE
There's no mysqlclient library on windows

### ISSUE THREAD

**Issue by Temtaime** [Paxa/mysql.d#7]
From dub.json :  "libs": ["mysqlclient"],
But there's no mysqlclient library on windows, it's named libmysql

Also in binding.d there's corresponding pragmas.
Please remove that section from dub package file - i cannot use mysql.d because of this error

**Comment by Paxa** [comment]
Thank you for bringing this up, I don't have easy solution to test it on windows.

I try to make a fix, can you please try (version 0.3.2)

I made it as:
```
  "libs-posix": ["mysqlclient"],
  "libs-windows": ["libmysql"],
```
