### ISSUE TITLE
MYSQL_FIELD

### ISSUE THREAD

**Issue by dazoe** [Paxa/mysql.d#8]
I believe there is a mistake in the definition of MYSQL_FIELD, it took me a while to track down.
```
        unsigned long length;       /* Width of column (create length) */
        unsigned long max_length;   /* Max width for selected set */
```
should be 
```
        size_t length;       /* Width of column (create length) */
        size_t max_length;   /* Max width for selected set */
```

this only effects 32-bit because unsigned long in 32 bit c is 4 bytes not 8

I hope this makes sense...

**Comment by Paxa** [comment]
Good catch, thanks
I never try it with 32bit
Will fix it

**Comment by Paxa** [comment]
Please try latest commit
